"""Regenerate the conformance fixtures in tests/conformance/fixtures/.

Builds both oracles, runs them over every code point and over the corpus,
cross-checks them, and writes the fixtures. ICU (built with the patches in
icu/patches/) is the primary oracle: the fixtures hold its results. The Rust
oracle is an independent implementation; every difference between the two
must fall under a named rule in agreement.py, or generation fails.

Run from the repository root, with Python 3.12 or later:

    uv run --no-project --python 3.14 python -m tools.oracles.generate

Pass --check to compare against the committed fixtures instead of writing.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from tools.oracles import agreement, corpus, rust_regen
from tools.unicode_sources import UNICODE_VERSION, fetch_all

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FIXTURES = ROOT / "tests" / "conformance" / "fixtures"

ICU_SOURCE_VERSION = re.search(
    r"^ICU_VERSION=(\S+)$", (HERE / "icu" / "build.sh").read_text(), re.MULTILINE
)


def hex_seq(text: str) -> str:
    return " ".join(f"{ord(c):04X}" for c in text)


def run(args: list[str | Path]) -> str:
    result = subprocess.run([str(a) for a in args], capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"{Path(args[0]).name} {args[1]} failed:\n{result.stderr}")
    return result.stdout


def build_icu() -> Path:
    return Path(run([HERE / "icu" / "build.sh"]).strip().splitlines()[-1])


def build_rust() -> Path:
    rust_regen.main()
    manifest = HERE / "rust" / "Cargo.toml"
    subprocess.run(
        [
            "cargo",
            "build",
            "--quiet",
            "--release",
            "--locked",
            "--manifest-path",
            manifest,
        ],
        check=True,
    )
    return HERE / "rust" / "target" / "release" / "confusable-oracle"


def header(name: str, description: list[str], columns: list[str], icu: str) -> str:
    lines = [
        f"# {name}: confusable conformance fixture, Unicode {UNICODE_VERSION}.",
        "# Generated by tools/oracles/generate.py from ICU",
        f"# {icu} with tools/oracles/icu/patches applied. Do not edit by hand.",
        "# Derived from Unicode data: see LICENSES/Unicode-3.0.txt.",
        "#",
        *(f"# {line}" if line else "#" for line in description),
        "#",
        "# Code point sequences are space-separated hex. Fields are tab-separated.",
        *(f"# Column {i}: {column}" for i, column in enumerate(columns, 1)),
    ]
    return "\n".join(lines) + "\n"


def same_as(value: str, reference: str) -> str:
    """Write "=" for a column that repeats an earlier one, to keep files small."""
    return "=" if value == reference else value


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="diff instead of writing")
    args = parser.parse_args()
    # Not sys.version_info itself, which mypy would treat as a platform check.
    if tuple(sys.version_info) < (3, 12):
        raise SystemExit("generate.py needs Python 3.12 or later")

    sources = fetch_all()
    confusables = sources["security/confusables.txt"]
    icu_oracle, rust_oracle = build_icu(), build_rust()

    icu_info = dict(line.split("\t") for line in run([icu_oracle, "info"]).splitlines())
    if not UNICODE_VERSION.startswith(icu_info["unicode"]):
        raise SystemExit(f"ICU implements Unicode {icu_info['unicode']}")
    for crate, version in (
        line.split("\t") for line in run([rust_oracle, "info"]).splitlines()
    ):
        if version != UNICODE_VERSION:
            raise SystemExit(f"{crate} implements Unicode {version}")
    assert ICU_SOURCE_VERSION is not None
    icu_label = f"{icu_info['icu']} (icu4c-{ICU_SOURCE_VERSION.group(1)} sources)"

    pools = corpus.Pools(sources)
    strings = corpus.strings(pools)
    pairs = corpus.pairs(pools, strings)

    with tempfile.TemporaryDirectory() as work:
        strings_in = Path(work) / "strings.txt"
        strings_in.write_text("".join(hex_seq(s) + "\n" for s in strings))
        pairs_in = Path(work) / "pairs.txt"
        pairs_in.write_text("".join(f"{hex_seq(a)}\t{hex_seq(b)}\n" for a, b in pairs))

        icu = {
            "skeleton": run([icu_oracle, "skeleton-codepoints", confusables]),
            "skeleton-rtl": run([icu_oracle, "skeleton-rtl-codepoints", confusables]),
            "nfd": run([icu_oracle, "nfd-codepoints"]),
            "properties": run([icu_oracle, "properties"]),
            "strings": run([icu_oracle, "strings", confusables, strings_in]),
            "pairs": run([icu_oracle, "pairs", confusables, pairs_in]),
        }
        rust = {
            "skeleton": run([rust_oracle, "skeleton-codepoints"]),
            "nfd": run([rust_oracle, "nfd-codepoints"]),
            "properties": run([rust_oracle, "properties"]),
            "strings": run([rust_oracle, "strings", strings_in]),
        }

    report = agreement.cross_check(strings, icu, rust)

    files = render(strings, pairs, icu, report, icu_label)
    files["GraphemeBreakTest.txt"] = sources[
        "ucd/auxiliary/GraphemeBreakTest.txt"
    ].read_text(encoding="utf-8")
    if args.check:
        stale = [
            name
            for name, text in files.items()
            if not (FIXTURES / name).exists()
            or (FIXTURES / name).read_text(encoding="utf-8") != text
        ]
        if stale:
            raise SystemExit(f"fixtures differ from a fresh run: {', '.join(stale)}")
        print("fixtures match a fresh run")
        return
    shutil.rmtree(FIXTURES, ignore_errors=True)
    FIXTURES.mkdir(parents=True)
    for name, text in files.items():
        (FIXTURES / name).write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(files)} fixtures to {FIXTURES.relative_to(ROOT)}")


def render(
    strings: list[str],
    pairs: list[tuple[str, str]],
    icu: dict[str, str],
    report: str,
    icu_label: str,
) -> dict[str, str]:
    files = {}
    files["skeleton.txt"] = (
        header(
            "skeleton.txt",
            [
                "skeleton(X) for every single code point X, surrogates excluded.",
                "For one code point, bidiSkeleton(LTR, X) equals internalSkeleton(X);",
                "the oracle verifies that for every code point.",
                "Code points not listed are their own skeleton. An empty column 2",
                "means the skeleton is empty (Default_Ignorable_Code_Point).",
            ],
            ["code point", "skeleton"],
            icu_label,
        )
        + icu["skeleton"]
    )
    files["skeleton-rtl.txt"] = (
        header(
            "skeleton-rtl.txt",
            [
                "bidiSkeleton(RTL, X) for the single code points where it differs",
                "from skeleton(X): mirrored characters in a right-to-left paragraph.",
            ],
            ["code point", "bidiSkeleton(RTL, X)"],
            icu_label,
        )
        + icu["skeleton-rtl"]
    )
    files["nfd.txt"] = (
        header(
            "nfd.txt",
            [
                "NFD of every single code point that NFD changes, surrogates",
                "excluded. The Rust oracle agrees on every code point.",
            ],
            ["code point", "NFD"],
            icu_label,
        )
        + icu["nfd"]
    )
    files["properties.txt"] = (
        header(
            "properties.txt",
            [
                "Character properties as ICU reports them, in UCD-style ranges.",
                'Each "## Name<TAB>default=Value" line starts a property; code',
                "points not listed in it have the default value. Script codes are",
                "ISO 15924; Script_Extensions is listed only where it differs from",
                "{Script}; Identifier_Type lists all types, sorted.",
            ],
            ["code point or range", "value"],
            icu_label,
        )
        + icu["properties"]
    )

    rows = []
    for text, line in zip(strings, icu["strings"].splitlines(), strict=True):
        ltr, internal, rtl, nfd, *rest = line.split("\t")
        source = hex_seq(text)
        rows.append(
            "\t".join(
                [
                    source,
                    ltr,
                    same_as(internal, ltr),
                    same_as(rtl, ltr),
                    same_as(nfd, source),
                    *rest,
                ]
            )
        )
    files["strings.txt"] = header(
        "strings.txt",
        [
            "Per-string results for the corpus: the curated attacks in",
            "tests/conformance/attacks.py, then seeded generated strings.",
            '"=" in a column means: the same as the column named in brackets.',
            "Restriction levels use the UTS #39 section 5.2 names; the identifier",
            "profile is the General Security Profile (Identifier_Status=Allowed).",
            "Column 8 lists the ICU checks that fail: CHAR_LIMIT (a character",
            "outside the profile), INVISIBLE (the same nonspacing mark twice in a",
            "row), MIXED_NUMBERS (digits from more than one decimal system),",
            "HIDDEN_OVERLAY (a mark hidden by its base). Column 9 lists the zero",
            "digit of each decimal system used. Column 10 lists grapheme cluster",
            "boundaries as code point offsets.",
        ],
        [
            "input",
            "skeleton = bidiSkeleton(LTR)",
            "internalSkeleton [2]",
            "bidiSkeleton(RTL) [2]",
            "NFD [1]",
            "resolved script set (ISO 15924; ALL; empty)",
            "restriction level",
            "failed ICU checks",
            "decimal zeros",
            "grapheme boundaries",
        ],
        icu_label,
    ) + "".join(row + "\n" for row in rows)

    pair_rows = []
    for (a, b), line in zip(pairs, icu["pairs"].splitlines(), strict=True):
        ltr, internal, rtl = line.split("\t")
        pair_rows.append(
            "\t".join(
                [hex_seq(a), hex_seq(b), ltr, same_as(internal, ltr), same_as(rtl, ltr)]
            )
        )
    files["pairs.txt"] = header(
        "pairs.txt",
        [
            "Confusable classes of string pairs (UTS #39 section 4): a space-",
            "separated subset of SINGLE_SCRIPT, MIXED_SCRIPT and WHOLE_SCRIPT,",
            'empty when the pair is not confusable. "=" means the same as [3].',
        ],
        [
            "string A",
            "string B",
            "confusable (skeleton)",
            "by internalSkeleton [3]",
            "by bidiSkeleton(RTL) [3]",
        ],
        icu_label,
    ) + "".join(row + "\n" for row in pair_rows)

    files["agreement.txt"] = report
    return files


if __name__ == "__main__":
    main()
